server:
  port: 8003
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: service-vod
aliyun:
  oss:
    file:
      keyid: LTAI5tKzcuNvyr8HXizh7XkB
      keysecret: 3l95gHC61TRFIXcYaHh6VJWPKXBLmR