server:
  port: 8004
spring:
  application:
    name: service-cms
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yundream
    username: root
    password: 651490
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: localhost
    port: 6379
    timeout: 1800000
    jedis:
      pool:
        max-active: 20
        max-idle: 5
        min-idle: 0
mybatis-plus:
  mapper-locations: classpath:com/tminto/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl