server:
  port: 8005
spring:
  application:
    name: service-cms
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8080
  redis:
    host: localhost
    port: 6379
    timeout: 1800000
    jedis:
      pool:
        max-active: 20
        max-idle: 5
        min-idle: 0